apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q61epeduj-go 
  janus-idp.io/tekton: q61epeduj-go
  backstage.io/kubernetes-id: q61epeduj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q61epeduj-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  